name: Application Health Check (Periodic)
on:
  push:
    branches:
      - master
  schedule:
    - cron: "10 14 * 9 *
jobs:
  health_check:
    runs-on: ubuntu-20.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2.2
        with:
          # Check the following URLs one by one sequentially
          url: https://example.com|https://pokedex30309.herokuapp.com/
