name: Application Health Check (Periodic)
on:
  push:
    branches:
      - master
  schedule:
    - cron: "* * * * *"
jobs:
  health_check:
    runs-on: ubuntu-20.04
    # steps:
    #   - name: Check the deployed service URL
    #     uses: jtalk/url-health-check-action@v2
    #     with:
    #       url: https://obscure-ocean-02441.herokuapp.com/health
      steps:
        - name: URL Health Check
          uses: Jtalk/url-health-check-action@v2.2
          with:
          # Check the following URLs one by one sequentially
            url: https://example.com|http://example.com

